export const userData = [
  {
    name: 'Tom',
    email: 'tom@gmail.com',
    password: 'tom123',
  },
];

export const productsData = [
  {
    title: "Whatever People Say I Am, That's What I'm Not",
    image:
      'https://upload.wikimedia.org/wikipedia/en/5/5f/Whatever_People_Say_I_Am%2C_That%27s_What_I%27m_Not.jpg',
    artist: 'Arctic Monkeys',
    price: 19.99,
    year: 2006,
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'The View From the Afternoon',
      'I Bet That You Look Good on the Dancefloor',
      'Fake Tales of San Francisco',
      'Dancing Shoes',
      "You Probably Coudn't See for the Lights but You Were Staring Straight at Me",
      'Still Take You Home',
      'Riot Van',
      'Red Light Indicates Doors Are Secured',
      'Mardy Bum',
      'Perhaps Vampies Is a Bit Strong But...',
      'When the Sun Goes Down',
      'From the Ritz to the Rubble',
      'A Certain Romance',
    ],
  },
  {
    title: 'Favourite Worst Nightmare',
    image:
      'https://upload.wikimedia.org/wikipedia/en/a/ae/Favourite_Worst_Nightmare.jpg',
    artist: 'Arctic Monkeys',
    price: 19.99,
    year: 2007,
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Brianstorm',
      'Teddy Picker',
      'D is for Dangerous',
      'Balaclava',
      'Fluorescent Adolescent',
      'Only Ones Who Know',
      'Do Me a Favour',
      'This House Is a Circus',
      'If You Were There, Beware',
      'The Bad Thing',
      'Old Yellow Bricks',
      '505',
    ],
  },
  {
    title: 'Humbug',
    image:
      'https://upload.wikimedia.org/wikipedia/en/2/20/Arcticmonkeys-humbug.jpg',
    artist: 'Arctic Monkeys',
    price: 19.99,
    year: 2009,
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'My Propellor',
      'Crying Lightning',
      'Dangerous Animals',
      'Secret Door',
      'Potion Approching',
      'Fire and the Thud',
      'Cornerstone',
      'Dance Little Liar',
      'Pretty Visitors',
      "The Jeweller's Hands",
    ],
  },
  {
    title: 'Suck It and See',
    image:
      'https://images-na.ssl-images-amazon.com/images/I/51QTqyFN%2B%2BL._AC_SL1417_.jpg',
    artist: 'Arctic Monkeys',
    price: 19.99,
    year: 2011,
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      "She's Thunderstorms",
      'Black Treacle',
      'Brick by Brick',
      'The Hellcat Spangled Shalalala',
      "Don't Sit Down 'Cause I've Moved Your Chair",
      'Library Pictures',
      'All My Own Stunts',
      'Reckless Serenade',
      'Piledriver Waltz',
      'Love Is a Laserquest',
      'Suck It and See',
      "That's Where You're Wrong",
    ],
  },
  {
    title: 'AM',
    image:
      'https://images-na.ssl-images-amazon.com/images/I/71hEtk3aCpL._AC_SY355_.jpg',
    artist: 'Arctic Monkeys',
    price: 19.99,
    year: 2013,
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Do I Wanna Know?',
      'R U Mine?',
      'One For the Road',
      'Arabella',
      'I Want It All',
      'No.1 Party Anthem',
      'Mad Sounds',
      'Fireside',
      "Why'd You Only Call Me When You're High?",
      'Snap Out of It',
      'Knee Socks',
      'I Wanna Be Yours',
    ],
  },
  {
    title: 'Royal Blood',
    image:
      'https://cdn.hmv.com/r/w-1280/hmv/files/8e/8ed1f219-9fdb-4463-a766-bd67c0923d6b.jpg',
    artist: 'Royal Blood',
    price: 19.99,
    year: 2014,
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Out of the Black',
      'Come On Over',
      'Figure It Out',
      'You Can Be So Cruel',
      'Blood Hands',
      'Little Monster',
      'Loose Change',
      'Careless',
      'Ten Tonne Skeleton',
      'Better Strangers',
    ],
  },
  {
    title: 'Currents',
    artist: 'Tame Impala',
    image:
      'https://images-na.ssl-images-amazon.com/images/I/A1LVEJikmZL._AC_SL1500_.jpg',
    price: 24.99,
    year: 2015,
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Let It Happen',
      'Nangs',
      'The Moment',
      "Yes I'm Changing",
      'Eventually',
      'Gossip',
      'The Less I Know the Better',
      'Past Life',
      'Disciples',
      "'Cause I'm a Man",
      'Reality in Motion',
      'Love/Paranoia',
      'New Person, Same Old Mistakes',
    ],
  },
  {
    title: "Who's Next",
    artist: 'The Who',
    image:
      'https://www.thisdayinmusic.com/wp-content/uploads/2018/05/whos-next.jpg',
    price: 19.99,
    year: 1971,
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      "Baba O'Riley",
      'Bargain',
      "Love Ain't for Keeping",
      'My Wife',
      'The Song Is Over',
      'Getting in Tune',
      'Going Mobile',
      'Behind Blue Eyes',
      "Won't Get Fooled Again",
    ],
  },
  {
    title: 'Breakfast in America',
    image:
      'https://upload.wikimedia.org/wikipedia/en/c/c4/Supertramp_-_Breakfast_in_America.jpg',
    artist: 'Supertramp',
    price: 22.99,
    year: 1979,
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Gone Hollywood',
      'The Logical Song',
      'Goodbye Stranger',
      'Breakfast in America',
      'Oh Darling',
      'Take the Long Way Home',
      'Lord Is It Mine',
      'Just Another Nervous Wreck',
      'Casual Conversations',
      'Child of Vision',
    ],
  },
  {
    title: 'Dark Side of the Moon',
    image:
      'https://images-na.ssl-images-amazon.com/images/I/51UtWpxbNYL._AC_SL1500_.jpg',
    artist: 'Pink Floyd',
    price: 19.99,
    year: 1973,
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Speak to Me',
      'Breathe',
      'On the Run',
      'Time',
      'The Great Gig in the Sky',
      'Money',
      'Us and Them',
      'Any Colour You Like',
      'Brain Damage',
      'Eclipse',
    ],
  },
  {
    title: 'Led Zeppelin I',
    artist: 'Led Zeppelin',
    image:
      'https://images-na.ssl-images-amazon.com/images/I/51SUWsbmnHL._AC_.jpg',
    price: 14.99,
    year: 1969,
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Good Times Bad Times',
      "Babe I'm Gonna Leave You",
      'You Shook Me',
      'Dazed and Confused',
      'Your Time Is Gonna Come',
      'Black Mountain Side',
      'Communication Breakdown',
      "I Can't Quit You Baby",
      'How Many More Times',
    ],
  },
  {
    title: 'Costello Music',
    artist: 'The Fratellis',
    image:
      'https://upload.wikimedia.org/wikipedia/en/c/c8/TheFratellis-CostelloMusic.jpg',
    price: 19.99,
    year: 2006,
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Henrietta',
      'Flathead',
      'Cuntry Boys & City Girls',
      'Whistle for the Choir',
      'Chelsea Dagger',
      'For the Girl',
      'Doginabag',
      'Creepin Up The Backstairs',
      'Vince the Loveable Stoner',
      'Everybody Knows You Cried Last Night',
      'Baby Fratelli',
      'Got Ma Nuts from a Hippy',
      'Ole Black ‘n’ Blue Eyes',
    ],
  },
];
