export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const LOADING_PRODUCT = 'LOADING_PRODUCT';
export const ERROR_PRODUCTS = 'ERROR_PRODUCTS';
export const ERROR_PRODUCT = 'ERROR_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
